//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTuneServiceManager.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTuneServiceManager.Localization.MainFormStrings", typeof(MainFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the computer on the local network..
        /// </summary>
        internal static string INFO_LABEL_COMPUTER {
            get {
                return ResourceManager.GetString("INFO_LABEL_COMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuneServer Windows Service manager - github.com/clearz/iTuneService.
        /// </summary>
        internal static string INFO_LABEL_DEFAULT {
            get {
                return ResourceManager.GetString("INFO_LABEL_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs and starts the iTuneServer Windows Service..
        /// </summary>
        internal static string INFO_LABEL_INSTALL {
            get {
                return ResourceManager.GetString("INFO_LABEL_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the iTuneServer Application (Only if service is stopped or not installed).
        /// </summary>
        internal static string INFO_LABEL_OPEN {
            get {
                return ResourceManager.GetString("INFO_LABEL_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the Windows account selected above..
        /// </summary>
        internal static string INFO_LABEL_PASS {
            get {
                return ResourceManager.GetString("INFO_LABEL_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype the password to confirm it..
        /// </summary>
        internal static string INFO_LABEL_RPASS {
            get {
                return ResourceManager.GetString("INFO_LABEL_RPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the iTuneServer executable file..
        /// </summary>
        internal static string INFO_LABEL_SELECT {
            get {
                return ResourceManager.GetString("INFO_LABEL_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the iTuneServer Windows Service..
        /// </summary>
        internal static string INFO_LABEL_START {
            get {
                return ResourceManager.GetString("INFO_LABEL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the iTuneServer Windows Service..
        /// </summary>
        internal static string INFO_LABEL_STOP {
            get {
                return ResourceManager.GetString("INFO_LABEL_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalls the iTuneServer Windows Service (Not this manager app).
        /// </summary>
        internal static string INFO_LABEL_UNINSTALL {
            get {
                return ResourceManager.GetString("INFO_LABEL_UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the account that has access to the music you want to be able to play..
        /// </summary>
        internal static string INFO_LABEL_USER {
            get {
                return ResourceManager.GetString("INFO_LABEL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been provisionally confirmed..
        /// </summary>
        internal static string INFO_LABEL_VPASS {
            get {
                return ResourceManager.GetString("INFO_LABEL_VPASS", resourceCulture);
            }
        }
    }
}
